// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcWrxWyjcPQB5T6cLNyOZJvd1QKHkZM3w',
    appId: '1:694414843228:web:0ab9fb3f44b98a06cdf599',
    messagingSenderId: '694414843228',
    projectId: 'taikichu-app-c8dcd',
    authDomain: 'taikichu-app-c8dcd.firebaseapp.com',
    storageBucket: 'taikichu-app-c8dcd.firebasestorage.app',
    measurementId: 'G-1SH3KCDK45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtde-oMJc8lV_w-UMfQ9qj_Kx6x0yMIaQ',
    appId: '1:694414843228:android:49642db38b3f4a7bcdf599',
    messagingSenderId: '694414843228',
    projectId: 'taikichu-app-c8dcd',
    storageBucket: 'taikichu-app-c8dcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7mBjWfucD5YINtuXQ4QOazfNOwhuz8gs',
    appId: '1:694414843228:ios:a4bae6772b4f934ccdf599',
    messagingSenderId: '694414843228',
    projectId: 'taikichu-app-c8dcd',
    storageBucket: 'taikichu-app-c8dcd.firebasestorage.app',
    iosBundleId: 'com.example.taikichuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7mBjWfucD5YINtuXQ4QOazfNOwhuz8gs',
    appId: '1:694414843228:ios:a4bae6772b4f934ccdf599',
    messagingSenderId: '694414843228',
    projectId: 'taikichu-app-c8dcd',
    storageBucket: 'taikichu-app-c8dcd.firebasestorage.app',
    iosBundleId: 'com.example.taikichuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcWrxWyjcPQB5T6cLNyOZJvd1QKHkZM3w',
    appId: '1:694414843228:web:34212bc8608f0338cdf599',
    messagingSenderId: '694414843228',
    projectId: 'taikichu-app-c8dcd',
    authDomain: 'taikichu-app-c8dcd.firebaseapp.com',
    storageBucket: 'taikichu-app-c8dcd.firebasestorage.app',
    measurementId: 'G-BW59JP3M6E',
  );

}