// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqkvqUcRPkTL5ehgXqkWtRdomSY_jBrDc',
    appId: '1:903887414245:web:a511fdf8b090ab4d95450c',
    messagingSenderId: '903887414245',
    projectId: 'taikichu-app',
    authDomain: 'taikichu-app.firebaseapp.com',
    storageBucket: 'taikichu-app.firebasestorage.app',
    measurementId: 'G-HYVH44DFLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEnIlcyDaCqRaDpQ5ISywb6aeu3x6yDRs',
    appId: '1:903887414245:android:8c35f045dc0be89e95450c',
    messagingSenderId: '903887414245',
    projectId: 'taikichu-app',
    storageBucket: 'taikichu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1-8eOBDTvJhSxrPcyklS-bmz06CC9aCk',
    appId: '1:903887414245:ios:0e6f26439e02478f95450c',
    messagingSenderId: '903887414245',
    projectId: 'taikichu-app',
    storageBucket: 'taikichu-app.firebasestorage.app',
    iosBundleId: 'com.example.taikichuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1-8eOBDTvJhSxrPcyklS-bmz06CC9aCk',
    appId: '1:903887414245:ios:0e6f26439e02478f95450c',
    messagingSenderId: '903887414245',
    projectId: 'taikichu-app',
    storageBucket: 'taikichu-app.firebasestorage.app',
    iosBundleId: 'com.example.taikichuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqkvqUcRPkTL5ehgXqkWtRdomSY_jBrDc',
    appId: '1:903887414245:web:9085abe6e47e995f95450c',
    messagingSenderId: '903887414245',
    projectId: 'taikichu-app',
    authDomain: 'taikichu-app.firebaseapp.com',
    storageBucket: 'taikichu-app.firebasestorage.app',
    measurementId: 'G-D81L9D2R70',
  );
}
